In [36]:
import pandas as pd
import sys
import os
sys.path.insert(0,"../")

In [46]:
# first get the training predictions
coin = "matic"
filename = "_all_predictions.csv"
file_name = coin + filename

In [47]:
file_name

'matic_all_predictions.csv'

In [48]:
training_predictions_df = pd.read_csv("./training_configs/"+file_name)

In [49]:
training_predictions_df.head()

,date,nbeats_matic_lookback_15_window_5_std_1.25_num_add_dfs_2,tcn_matic_lookback_15_window_5_std_1.25_num_add_dfs_2,nbeats_matic_lookback_30_window_5_std_1.25_num_add_dfs_2,tcn_matic_lookback_30_window_5_std_1.25_num_add_dfs_2,nbeats_matic_lookback_45_window_5_std_1.25_num_add_dfs_2,tcn_matic_lookback_45_window_5_std_1.25_num_add_dfs_2,date_prediction_for,stacking_prediction
0,2021-02-01,0.0,0.0,0.0,0.0,0.0,0.0,2021-02-08,0.0
1,2021-02-02,0.0,0.0,0.0,0.0,0.0,0.0,2021-02-09,0.0
2,2021-02-03,0.0,0.0,0.0,0.0,0.0,0.0,2021-02-10,0.0
3,2021-02-08,0.0,0.0,0.0,0.0,0.0,0.0,2021-02-15,0.0
4,2021-02-09,0.0,0.0,0.0,0.0,0.0,0.0,2021-02-16,0.0

In [50]:
# read in current predictions
current_predictions  =  pd.read_csv("../tmp/"+file_name)

In [51]:
current_predictions.head()

,date,nbeats_matic_lookback_15_window_5_std_1.25_num_add_dfs_2,tcn_matic_lookback_15_window_5_std_1.25_num_add_dfs_2,nbeats_matic_lookback_30_window_5_std_1.25_num_add_dfs_2,tcn_matic_lookback_30_window_5_std_1.25_num_add_dfs_2,nbeats_matic_lookback_45_window_5_std_1.25_num_add_dfs_2,tcn_matic_lookback_45_window_5_std_1.25_num_add_dfs_2,date_prediction_for,nbeats_matic_lookback_45_window_5_std_1.25_num_add_dfs_4,stacking_prediction,tcn_matic_lookback_30_window_5_std_1.25_num_add_dfs_4,tcn_matic_lookback_15_window_5_std_1.25_num_add_dfs_4,nbeats_matic_lookback_15_window_5_std_1.25_num_add_dfs_4,nbeats_matic_lookback_30_window_5_std_1.25_num_add_dfs_4,tcn_matic_lookback_45_window_5_std_1.25_num_add_dfs_4,test_model_lookback_1
0,2022-04-06,1.603002,1.572611,1.667775,1.516322,1.744396,1.575042,2022-04-13,0.000000,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.0
1,2022-04-07,1.524049,1.523256,1.590269,1.346501,1.593843,1.207000,2022-04-14,0.000000,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.0
2,2022-04-08,1.497505,1.541635,1.562124,1.384738,1.666282,1.314347,2022-04-15,0.000000,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.0
3,2022-04-10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2022-04-17,1.492088,0.0,1.350004,1.46584,1.321284,1.355818,1.394621,0.0
4,2022-04-11,1.728103,1.538732,1.489681,1.187060,1.680922,1.213888,2022-04-18,0.000000,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.0

## combine both DFs

In [52]:
updated_current_predictions_df = pd.concat([training_predictions_df, current_predictions]).fillna(0)

In [53]:
updated_current_predictions_df

,date,nbeats_matic_lookback_15_window_5_std_1.25_num_add_dfs_2,tcn_matic_lookback_15_window_5_std_1.25_num_add_dfs_2,nbeats_matic_lookback_30_window_5_std_1.25_num_add_dfs_2,tcn_matic_lookback_30_window_5_std_1.25_num_add_dfs_2,nbeats_matic_lookback_45_window_5_std_1.25_num_add_dfs_2,tcn_matic_lookback_45_window_5_std_1.25_num_add_dfs_2,date_prediction_for,stacking_prediction,nbeats_matic_lookback_45_window_5_std_1.25_num_add_dfs_4,tcn_matic_lookback_30_window_5_std_1.25_num_add_dfs_4,tcn_matic_lookback_15_window_5_std_1.25_num_add_dfs_4,nbeats_matic_lookback_15_window_5_std_1.25_num_add_dfs_4,nbeats_matic_lookback_30_window_5_std_1.25_num_add_dfs_4,tcn_matic_lookback_45_window_5_std_1.25_num_add_dfs_4,test_model_lookback_1
0,2021-02-01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2021-02-08,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2021-02-02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2021-02-09,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2021-02-03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2021-02-10,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2021-02-08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2021-02-15,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2021-02-09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2021-02-16,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,2022-05-26,0.420218,0.714486,0.567428,0.574231,0.444978,0.468057,2022-06-02,0.653919,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,2022-05-27,0.434525,0.454004,0.463123,0.528295,0.554202,0.499132,2022-06-03,0.623008,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,2022-05-28,0.426301,0.401293,0.404902,0.330573,0.483008,0.660243,2022-06-04,0.606110,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,2022-05-29,0.477194,0.404975,0.361086,0.839844,0.486688,0.829640,2022-06-05,0.608423,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,2022-05-30,0.465878,0.636693,0.318536,0.885544,0.318841,0.697355,2022-06-06,0.615932,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# save filename

"../tmp/"+file_name

In [45]:
updated_current_predictions_df.to_csv("../tmp/"+file_name, index=False)